version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php:8.0-apache
    container_name: php-container
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump.sql:/docker-entrypoint-initdb.d/db-dump.sql

volumes: {}
